# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '18.2'

install! 'cocoapods', warn_for_unused_master_specs_repo: false

target 'ParkingLot' do
  use_frameworks!

  # Pods for ParkingLot
  pod 'SQLite.swift'
end